spring:
  application:
    name: projet42
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/projet42
    username: root
    password: Password123!
  jpa:
    properties:
      hibernate:.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # none
  documentation:
    swagger:
      enabled: true
