spring:
  application:
    name: projet42
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.54:3306/projet42
    username: userjovan
    password: Userjovan-69
  jpa:
    properties:
      hibernate:.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update # none
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: projet42-api
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://keycloak.doubli.fr:8443/realms/projet42
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.doubli.fr:8443/realms/projet42
          jwk-set-uri: https://keycloak.doubli.fr:8443/realms/projet42/protocol/openid-connect/certs

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


file:
  upload-dir: /var/p42/projet42/uploads
keycloak:
  auth-server-url: https://keycloak.doubli.fr:8443
  realm: projet42

